// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SykesCottagesTestAutomation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ThinkingOfBuying")]
    public partial class ThinkingOfBuyingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "ThinkingOfBuying.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "ThinkingOfBuying", "\tThinking of Buying content and functionality", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the Thinking of Buying page")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheThinkingOfBuyingPage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the Thinking of Buying page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given("I have navigated to the following page: letyourcottage/advice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table91 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table91.AddRow(new string[] {
                            "Holiday Let Information Centre"});
                table91.AddRow(new string[] {
                            "Browse categories"});
                table91.AddRow(new string[] {
                            "Beginner Guides to Buying a Holiday Home"});
                table91.AddRow(new string[] {
                            "Latest Guides and Articles"});
                table91.AddRow(new string[] {
                            "Services and Tools"});
                table91.AddRow(new string[] {
                            "Making a Fresh Start"});
                table91.AddRow(new string[] {
                            "Contact us"});
#line 7
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table91, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the Buying a Holiday Home page")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheBuyingAHolidayHomePage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the Buying a Holiday Home page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
 testRunner.Given("I have navigated to the following page: letyourcottage/advice/buying-a-holiday-ho" +
                        "me", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table92 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table92.AddRow(new string[] {
                            "Buying a Holiday Home"});
                table92.AddRow(new string[] {
                            "Where to Buy"});
                table92.AddRow(new string[] {
                            "General"});
                table92.AddRow(new string[] {
                            "Beginner Guides to Buying a Holiday Home"});
                table92.AddRow(new string[] {
                            "Intermediate Guides to Buying a Holiday Home"});
                table92.AddRow(new string[] {
                            "Services and Tools"});
                table92.AddRow(new string[] {
                            "Converting a Listed Chapel Into a Holiday Let"});
                table92.AddRow(new string[] {
                            "Contact us"});
#line 20
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table92, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the Financial Guides page")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheFinancialGuidesPage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the Financial Guides page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
 testRunner.Given("I have navigated to the following page: letyourcottage/advice/financial-guides", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table93 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table93.AddRow(new string[] {
                            "Financial Guides"});
                table93.AddRow(new string[] {
                            "Regulations"});
                table93.AddRow(new string[] {
                            "Mortgages"});
                table93.AddRow(new string[] {
                            "Insurance"});
                table93.AddRow(new string[] {
                            "Taxes"});
                table93.AddRow(new string[] {
                            "Beginner Guides to Financials"});
                table93.AddRow(new string[] {
                            "Intermediate Guides to Financials"});
                table93.AddRow(new string[] {
                            "Advanced Guides to Financials"});
                table93.AddRow(new string[] {
                            "Services and Tools"});
                table93.AddRow(new string[] {
                            "Making an Income"});
                table93.AddRow(new string[] {
                            "Contact us"});
#line 34
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table93, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the Letting a Holiday Home page")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheLettingAHolidayHomePage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the Letting a Holiday Home page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 50
 testRunner.Given("I have navigated to the following page: letyourcottage/advice/holiday-letting-gui" +
                        "des", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table94 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table94.AddRow(new string[] {
                            "Letting a Holiday Home"});
                table94.AddRow(new string[] {
                            "Holiday Letting"});
                table94.AddRow(new string[] {
                            "Maximising Earnings"});
                table94.AddRow(new string[] {
                            "Running Your Holiday Let"});
                table94.AddRow(new string[] {
                            "Tips and Advice"});
                table94.AddRow(new string[] {
                            "Listing a Holiday Let"});
                table94.AddRow(new string[] {
                            "Beginner Guides to Letting a Holiday Home"});
                table94.AddRow(new string[] {
                            "Intermediate Guides to Letting a Holiday Home"});
                table94.AddRow(new string[] {
                            "Advanced Guides to Letting a Holiday Home"});
                table94.AddRow(new string[] {
                            "Services and Tools"});
                table94.AddRow(new string[] {
                            "Setting up a Holiday Let"});
                table94.AddRow(new string[] {
                            "Contact us"});
#line 51
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table94, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the Managing a Holiday Let page")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheManagingAHolidayLetPage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the Managing a Holiday Let page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 68
 testRunner.Given("I have navigated to the following page: letyourcottage/advice/managing-your-holid" +
                        "ay-let", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table95 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table95.AddRow(new string[] {
                            "Managing a Holiday Let"});
                table95.AddRow(new string[] {
                            "Why Sykes?"});
                table95.AddRow(new string[] {
                            "Services and Tools"});
                table95.AddRow(new string[] {
                            "Running Two Holiday Lets"});
                table95.AddRow(new string[] {
                            "Contact us"});
#line 69
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table95, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the Case Studies page")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheCaseStudiesPage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the Case Studies page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 79
 testRunner.Given("I have navigated to the following page: letyourcottage/advice/case-studies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table96 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table96.AddRow(new string[] {
                            "Owner Case Studies"});
                table96.AddRow(new string[] {
                            "Services and Tools"});
                table96.AddRow(new string[] {
                            "Contact us"});
#line 80
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table96, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the A Guide to Buying a Holiday Let page")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheAGuideToBuyingAHolidayLetPage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the A Guide to Buying a Holiday Let page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 88
 testRunner.Given("I have navigated to the following page: letyourcottage/advice/article/a-guide-to-" +
                        "buying-a-holiday-let", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table97 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table97.AddRow(new string[] {
                            "A Guide to Buying a Holiday Let"});
                table97.AddRow(new string[] {
                            "Let\'s Work Together"});
                table97.AddRow(new string[] {
                            "The key benefits of buying a holiday let"});
                table97.AddRow(new string[] {
                            "A guide to buying your holiday home"});
                table97.AddRow(new string[] {
                            "Where to buy your holiday home"});
                table97.AddRow(new string[] {
                            "Legalities"});
                table97.AddRow(new string[] {
                            "Taxes"});
                table97.AddRow(new string[] {
                            "What are the extra costs when you buy a holiday let?"});
                table97.AddRow(new string[] {
                            "Buying a Holiday Home General Guides"});
                table97.AddRow(new string[] {
                            "Contact us"});
#line 89
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table97, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the Are Holiday Lets a Good Investment pag" +
            "e")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheAreHolidayLetsAGoodInvestmentPage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the Are Holiday Lets a Good Investment pag" +
                    "e", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 103
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 104
 testRunner.Given("I have navigated to the following page: letyourcottage/advice/article/why-are-hol" +
                        "iday-lets-a-good-investment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table98 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table98.AddRow(new string[] {
                            "Are Holiday Lets a Good Investment?"});
                table98.AddRow(new string[] {
                            "Let\'s Work Together"});
                table98.AddRow(new string[] {
                            "Are holiday lets a good investment?"});
                table98.AddRow(new string[] {
                            "What types of holiday let mortgages are there?"});
                table98.AddRow(new string[] {
                            "What Return on Investment can you get from a holiday let?"});
                table98.AddRow(new string[] {
                            "Best places to buy a holiday home"});
                table98.AddRow(new string[] {
                            "How to maximise your income"});
                table98.AddRow(new string[] {
                            "Ready to get started?"});
                table98.AddRow(new string[] {
                            "Buying a Holiday Home General Guides"});
                table98.AddRow(new string[] {
                            "Contact us"});
#line 105
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table98, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The relevant sections are displayed on the Buying a Holiday Home Abroad vs. in th" +
            "e UK page")]
        [NUnit.Framework.CategoryAttribute("ThinkingOfBuying")]
        [NUnit.Framework.CategoryAttribute("TOBSmokeTest")]
        public void TheRelevantSectionsAreDisplayedOnTheBuyingAHolidayHomeAbroadVs_InTheUKPage()
        {
            string[] tagsOfScenario = new string[] {
                    "ThinkingOfBuying",
                    "TOBSmokeTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The relevant sections are displayed on the Buying a Holiday Home Abroad vs. in th" +
                    "e UK page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 119
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 120
 testRunner.Given("I have navigated to the following page: letyourcottage/advice/article/buying-a-ho" +
                        "liday-home-abroad-vs-uk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table99 = new TechTalk.SpecFlow.Table(new string[] {
                            "Element"});
                table99.AddRow(new string[] {
                            "Buying a Holiday Home Abroad vs. in the UK"});
                table99.AddRow(new string[] {
                            "Let\'s Work Together"});
                table99.AddRow(new string[] {
                            "Benefits of Holiday Letting in the UK"});
                table99.AddRow(new string[] {
                            "Disadvantages of Holiday Letting in the UK"});
                table99.AddRow(new string[] {
                            "Benefits of Holiday Letting Abroad"});
                table99.AddRow(new string[] {
                            "Disadvantages of Holiday Letting Abroad"});
                table99.AddRow(new string[] {
                            "Where to Buy Guides"});
                table99.AddRow(new string[] {
                            "Contact us"});
#line 121
 testRunner.Then("the relevant elements are dislpayed", ((string)(null)), table99, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
